### ISSUE TITLE
Still unable to use MSTL 

### ISSUE THREAD

**Issue by virsto** [KishManani/MSTL#2]
Thanks KishManani for your prompt reply :-)

When will MSTL be available in Statsmodels? Here is what I have installed as per your requirements.txt:

jupyterlab = 3.4.3
matplotlib = 3.5.2
numpy = 1.23.0
pandas = 1.4.0
seaborn = 0.11.2

Not sure how to access/use the following:

git+https://github.com/statsmodels/statsmodels.git@74836e9cf2198ac7a930146405da7239c0823a9b#egg=statsmodels

I did find your [MSTL code](https://www.statsmodels.org/devel/_modules/statsmodels/tsa/stl/mstl.html)

How can I install your MSTL code to execute without a virtual environment and Jupyter? Or, how can I install the latest Statsmodels code that you mentioned with your MSTL?

As you can probably tell by now, I am not that good with Git :-(

Please don't close this issue yet.

**Comment by KishManani** [comment]
Hi virsto! The best way to reproduce the results in the notebook would be to reproduce the environment that I've specified in the requirements.txt file and following the instructions in the README and running:

`pip install -r requirements.txt`

Alternatively, you might find it simpler to pip install the latest version of Statsmodels directly from GitHub:

`pip install git+https://github.com/statsmodels/statsmodels.git`

Let me know if that helps!

**Comment by virsto** [comment]
C:\python39>python -m pip install git+https://github.com/statsmodels/statsmodels.git
Collecting git+https://github.com/statsmodels/statsmodels.git
  Cloning https://github.com/statsmodels/statsmodels.git to c:\users\vs\appdata\local\temp\pip-req-build-53smj16r
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH

i have git and use the git console -- why does 'git' need to be in the path?

**Comment by virsto** [comment]
OK! Finally I see how to move forward on this issue., KishManani
I actually did not have git installed. I have now installed it. 

And just now finished the installation of Statsmodels 0.13.2 (from git)
And the following

`from statsmodels.tsa.seasonal import MSTL`  

executes correctly! Thank you for your patience KM :-)

**Comment by KishManani** [comment]
Great to hear it works now!
